services:
  postgres:
    image: postgres:17
    container_name: otp-postgres
    environment:
      POSTGRES_DB: otp_service
      POSTGRES_USER: otp_user
      POSTGRES_PASSWORD: otp_password
    ports:
      - "5432:5432"
    volumes:
      - otp_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U otp_user -d otp_service"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: otp-service
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      DB_URL: jdbc:postgresql://postgres:5432/otp_service
      DB_USERNAME: otp_user
      DB_PASSWORD: otp_password
      FLYWAY_LOCATIONS: classpath:db/migration
      TOKEN_SECRET: change-this-secret-to-long-random-value
      TOKEN_TTL_SECONDS: 3600
      OTP_EXPIRATION_SCHEDULER_INTERVAL_SECONDS: 60
    volumes:
      - ./otp-codes.txt:/app/otp-codes.txt

volumes:
  otp_postgres_data: