server.port=8082

db.url=jdbc:postgresql://localhost:5432/otp_service
db.username=
db.password=

flyway.locations=classpath:db/migration

token.secret=
token.ttl.seconds=3600

otp.expiration.scheduler.interval.seconds=60
