server.port=8082

db.url=jdbc:postgresql://localhost:5432/otp_service
db.username=otp_user
db.password=otp_password

flyway.locations=classpath:db/migration

token.secret=change-this-secret-to-long-random-value
token.ttl.seconds=3600